version: '2'

services:
  son-catalogue-repos:
    build:
      context: ./
      dockerfile: Dockerfile   
    links:
      - mongo
    environment:
      - ADAPTER_PORT=8081
    networks:
      - default
      - songtkusr_default
    ports:
      - "4002:4011"
    external_links:
      - sonata-adapter
    restart: always

  son-catalogue-repos-doc:
    image: registry.sonata-nfv.eu:5000/son-catalogue-repos
    ports:
      - "8800:8808"
    #command: [rake,yard]
    #command: [yard, server, -B, 0.0.0.0]
    restart: always

  mongo:  
    image: mongo:3.0.4
    volumes:
      - /db/data
    ports:
      - "27017"
    command: --smallfiles --rest
    restart: always

  mongoexpress:
    image: mongo-express
    links:
      - mongo:mongo
    ports:
      - "8090:8081"
    restart: always

networks:
  songtkusr_default:
    external: true



